import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { scale, verticalScale, responsiveFontSize, maxContainerWidth } from '../utils/responsive';

export default function AssignedIssuesScreen({ token, apiUrl, onBack }) {
  const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[remarks,setRemarks]=useState({});
  const load=useCallback(async()=>{try{const response=await fetch(`${apiUrl}/feedback?limit=100`,{headers:{Authorization:`Bearer ${token}`}});const result=await response.json();if(!response.ok)throw new Error(result.message);setRows(Array.isArray(result.data)?result.data:[])}catch(error){Alert.alert('Issues',error.message)}finally{setLoading(false);setRefreshing(false)}},[apiUrl,token]);
  useEffect(()=>{load()},[load]);
  const resolve=async issue=>{const resolutionRemark=remarks[issue._id]?.trim();if(!resolutionRemark)return Alert.alert('Solution required','Enter what solution was provided.');try{const response=await fetch(`${apiUrl}/feedback/${issue._id}/resolve`,{method:'PUT',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({resolutionRemark})});const result=await response.json();if(!response.ok)throw new Error(result.message);setRemarks(current=>({...current,[issue._id]:''}));await load()}catch(error){Alert.alert('Unable to resolve',error.message)}};
  return <SafeAreaView style={styles.safe}><View style={styles.head}><TouchableOpacity onPress={onBack}><Text style={styles.back}>‹ Back</Text></TouchableOpacity><View><Text style={styles.title}>Assigned Issues</Text><Text style={styles.sub}>Resolve customer issues with accountability</Text></View></View>{loading?<ActivityIndicator style={{marginTop:50}} color="#00796B"/>:<ScrollView contentContainerStyle={styles.body} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load()}}/>}>{rows.map(issue=><View key={issue._id} style={styles.card}><View style={styles.row}><Text style={styles.number}>{issue.issueNumber}</Text><Text style={[styles.status,issue.status==='resolved'&&styles.done]}>{issue.status}</Text></View><Text style={styles.subject}>{issue.subject}</Text><Text style={styles.meta}>{issue.partyId?.partyName||issue.salesmanId?.name||'General'} · {issue.priority}</Text><Text style={styles.description}>{issue.description}</Text>{issue.status!=='resolved'&&<><TextInput multiline style={styles.input} placeholder="Solution / resolution remark" value={remarks[issue._id]||''} onChangeText={value=>setRemarks(current=>({...current,[issue._id]:value}))}/><TouchableOpacity style={styles.button} onPress={()=>resolve(issue)}><Text style={styles.buttonText}>Resolve Issue</Text></TouchableOpacity></>}</View>)}{!rows.length&&<Text style={styles.empty}>No issues assigned to you.</Text>}</ScrollView>}</SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F9FC'},head:{padding: scale(16),backgroundColor:'#fff',borderBottomWidth:1,borderColor:'#E2E8F0',flexDirection:'row',gap: verticalScale(18),alignItems:'center'},back:{color:'#00796B',fontWeight:'700'},title:{fontSize: responsiveFontSize(19),fontWeight:'800',color:'#1A202C'},sub:{fontSize: responsiveFontSize(12),color:'#718096'},body:{padding: scale(16)},card:{backgroundColor:'#fff',padding: scale(15),borderRadius:12,marginBottom: verticalScale(12),elevation:1},row:{flexDirection:'row',justifyContent:'space-between'},number:{fontWeight:'800',color:'#00796B'},status:{textTransform:'uppercase',fontSize: responsiveFontSize(11),color:'#C05621'},done:{color:'#25855A'},subject:{fontSize: responsiveFontSize(16),fontWeight:'800',marginTop: verticalScale(8),color:'#1A202C'},meta:{fontSize: responsiveFontSize(12),color:'#718096',marginTop: verticalScale(3)},description:{color:'#4A5568',marginVertical: verticalScale(10)},input:{borderWidth:1,borderColor:'#CBD5E0',borderRadius:8,padding: scale(10),minHeight:70,textAlignVertical:'top'},button:{backgroundColor:'#00796B',borderRadius:8,padding: scale(12),alignItems:'center',marginTop: verticalScale(10)},buttonText:{color:'#fff',fontWeight:'800'},empty:{textAlign:'center',color:'#718096',marginTop: verticalScale(50)}});
